import os

BULLHORN_CLIENT_ID = os.environ["BULLHORN_CLIENT_ID"]
BULLHORN_CLIENT_SECRET = os.environ["BULLHORN_CLIENT_SECRET"]
BULLHORN_REDIRECT_URI = os.environ["BULLHORN_REDIRECT_URI"]
WEBFLOW_API_KEY = os.environ["WEBFLOW_API_KEY"]
WEBFLOW_COLLECTION_ID = os.environ["WEBFLOW_COLLECTION_ID"]
WEBFLOW_SITE_ID = os.environ["WEBFLOW_SITE_ID"]
